#
# BASE CONFIGURATION
#

# `base_url` should only be changed if your site isn't hosted at the root of a domain.
# `domain` is used to generate absolute URLs. (required to generate a valid feed)
#
#   Example:
#       http://my-site.com/
#           base_url: /
#           domain: my-site.com
#       http://my-site.com/my-blog/
#           base_url: /my-blog/
#           domain: my-site.com

base_url: /
domain:
# base_url: /taiwan.py/
# domain: lucemia.github.io


#
# METADATA
#

# Used in header meta tags and the site feed. (required to generate a valid feed)
author: Python Taiwan
# A description of your site to be used in header meta tags.
description: 我們是 Python 台灣使用者群組（簡稱 PyTUG - Python Taiwan User Group），由台灣的 Python 程式語言使用者、學習者或愛好者所組成。
# Used in the site feed.
email:
# Your site's subtitle.
subtitle: 台灣的Python社群
# Your site's title. (required to generate a valid feed)
title: Python Taiwan


#
# THIRD PARTY SETTINGS
#

# If you'd like to enable Google Analytics for your site, set this to your tracking code.
analytics: UA-43724158-1

#
# Chances are you probably don't need to touch anything below here.
#

archive_layout: archive.html
archives_url: /archives/
tag_layout: tag.html
tags_url: /archives/
